INSERT INTO GEN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (1, '*', '언어 구분', 'LANG', 0);
INSERT INTO GEN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (2, 'KR', '한국어', 'LANG', 1);
INSERT INTO GEN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (3, 'EN', '영어', 'LANG', 2);
INSERT INTO GEN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (4, 'CH', '중국어', 'LANG', 3);

INSERT INTO GEN_CHAT(CHAT_ID, TITLE, SYS_CREATE_DT, SYS_MODIFY_DT) VALUES (1, '기본', NOW(), NOW());

INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (1, 2000, '나만의 AI 템플릿 생성 프롬프트', '나만의 AI 템플릿 생성 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (2, 2000, '보고서 템플릿 생성 프롬프트', '보고서 템플릿 생성 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (3, 2000, 'LLM 질의 프롬프트', 'LLM 질의 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (4, 2000, 'AI 질의 프롬프트', 'AI 질의 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (5, 2000, '나만의 AI 질의 프롬프트', '나만의 AI 질의 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (6, 2000, '요약 프롬프트', '요약 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (7, 2000, '번역 프롬프트', '번역 프롬프트', 0.9, 0.2);
INSERT INTO GEN_PROMPT(PROMPT_ID, MAXIMUM_TOKENS, PROMPT_CONTENT, PROMPT_NAME, TEMPERATURE, TOP_P) VALUES (8, 2000, '보고서 생성 프롬프트', '보고서 생성 프롬프트', 0.9, 0.2);